# Generate TLU internal trigger with given rate in Hz
internal_trigger:
  internal_trigger_rate: 0

# Set operating mode of the DUT, supported are three operating modes 'aida', 'aidatrig' and 'eudet'
# Set unused DUT interfaces to off, false or None
dut_module:
  dut_1:
    mode: aida
  dut_2:
    mode: aida
  dut_3:
    mode: eudet
  dut_4:
    mode: off

trigger_inputs:
  # Threshold voltages for the trigger inputs in V.
  threshold:
    threshold_1: -0.1
    threshold_2: -0.1
    threshold_3: -0.1
    threshold_4: -0.1
    threshold_5: -0.1
    threshold_6: -0.1

  # Trigger Logic configuration accept a python expression for the trigger inputs.
  # The logic is set by using the variables for the input channels 'CH1', 'CH2', 'CH3', 'CH4', 'CH5' and 'CH6'
  # and the Python bitwise operators AND: '&', OR: '|', NOT: 'not' and so on. Dont forget to use brackets...
  trigger_inputs_logic: CH2 & CH4

  # TLU can trigger on a rising or falling edge. Trigger polarity is set using a string or boolean,
  # 'rising' corresponds to false (0) and 'falling' to true (1)
  trigger_polarity:
    polarity: falling

# Stretches and delays each trigger input signal for an number of clock cycles (corresponds to 6.25ns steps),
# The stretch and delay of all inputs is given as a list,
# each entry corresponding to an individual trigger input.
  trigger_signal_shape:
    stretch: [2, 2, 2, 2, 2, 2]
    delay: [0, 0, 0, 0, 0, 0]

# Enable the LEMO clock output using a boolean.
clock_lemo:
  enable_clock_lemo_output: on

# Set the four PMT control voltages in V
pmt_control:
  pmt_1: 0.8
  pmt_2: 0.8
  pmt_3: 0
  pmt_4: 0

# Save and generate interpreted data from the raw data set. Set to 'True' or 'False'.
# If no specific output path is provided, the data is saved in the default output data path (aidatlu/aidatlu/tlu_data).
save_data: True
output_data_path:

# zmq connection for status messages, leave it blank or set to off if not needed
zmq_connection: off  #"tcp://127.0.0.1:6500"

# Optional stop conditions can also be added to the configuration.
# These can be a timeout in seconds or a maximum output trigger number.
# If needed just uncomment the required stop condition in the example below:
# max_trigger_number: 1000000
# timeout: 60
