
converter :
    AIDA_TLU_Converter :
        kind : tlu_converter
        frontend : tcp://131.220.165.88:1500
        backend : tcp://127.0.0.1:7501
        threshold: 10

receiver :
    AIDA_TLU :
        kind : tlu_receiver
        frontend : tcp://127.0.0.1:7501
