[satellites]
[satellites.AidaTLU]

internal_trigger_rate = 0
dut_interfaces = ['aida', 'aida', 'off', 'off']

trigger_threshold = [-0.1, -0.1, -0.1, -0.1, -0.1, -0.1]
trigger_inputs_logic = 'CH1 and CH2'
trigger_polarity = 'falling'
trigger_signal_stretch = [2, 2, 2, 2, 2, 2]
trigger_signal_delay = [0, 0, 0, 0, 0, 0]

enable_clock_lemo_output = false
pmt_power = [0.8, 0.8, 0.0, 0.0]
output_data_path = ''
