name: tests

on:
  pull_request:
  push:
    branches: [main, development]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - name: Install dependencies
        run: |
          pip install -e .[test]
          pip install pytest

      - name: Test with pytest
        run: |
          pytest -sv
